---
json_rpc_url: "https://api.devnet.solana.com"
websocket_url: ""
keypair_path: ./target/deploy/net_authority-keypair.json
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed
